### ISSUE TITLE
Refactor Google auth

### ISSUE THREAD

**Issue by sim642** [sim642/potatonet#47]
- [x] Make success handler delegate to existing success handler on login (https://github.com/sim642/potatonet/commit/cb33c90866ca8d3a319eb1c96d711a5c4957f1e6#commitcomment-21225984)
- [x] Fix formatting (https://github.com/sim642/potatonet/commit/cb33c90866ca8d3a319eb1c96d711a5c4957f1e6#commitcomment-21225988)
- [x] Delegate `unsuccessfulAuthentication` to failure handler on registration failure, instead of redirecting itself (https://github.com/sim642/potatonet/commit/cb33c90866ca8d3a319eb1c96d711a5c4957f1e6#commitcomment-21226003)
- [x] Use `ConfigurationProperties` instead of `Environment` (https://github.com/sim642/potatonet/commit/cb33c90866ca8d3a319eb1c96d711a5c4957f1e6#commitcomment-21226071)
- [x] Simplify Google auth button by using an image
- [x] Change URL mappings to be more RESTful (https://github.com/sim642/potatonet/commit/cb33c90866ca8d3a319eb1c96d711a5c4957f1e6#commitcomment-21226106)

**Comment by Oja95** [comment]
Closed by b27a72c
