### ISSUE TITLE
Resecure Google auth for production profile

### ISSUE THREAD

**Issue by sim642** [sim642/potatonet#48]
https://github.com/sim642/potatonet/commit/cb33c90866ca8d3a319eb1c96d711a5c4957f1e6#commitcomment-21226087

- [x] Remove secret key from properties
- [x] Generate new key for production profile
- [x] Place new key directly into config properties on server

**Comment by Oja95** [comment]
Closed by 7839199c69b54334122c6e6c0aef9563606b24c4
